Repository 6th-NE-O-RDINARY-HACKATHON-Team-D/Dofarming-Server, pull requests merged in 2024-06, with the labels that each got.

#2 [setting] 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/✨feat.md
  .github/ISSUE_TEMPLATE/🆘help.md
  .github/ISSUE_TEMPLATE/🐛bug-report.md
  .github/ISSUE_TEMPLATE/🚑fix.md
  build.gradle
  src/main/java/neordinary/dofarming/DofarmingApplication.java
  src/main/java/neordinary/dofarming/api/controller/auth/AuthController.java
  src/main/java/neordinary/dofarming/api/controller/auth/dto/response/GetKakaoRes.java
  src/main/java/neordinary/dofarming/api/controller/auth/dto/response/PostSocialRes.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthConverter.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthService.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/auth/social/kakao/KakaoLoginService.java
  src/main/java/neordinary/dofarming/api/service/auth/social/kakao/KakaoLoginServiceImpl.java
  src/main/java/neordinary/dofarming/common/BaseEntity.java
  src/main/java/neordinary/dofarming/common/BaseResponse.java
  src/main/java/neordinary/dofarming/common/code/BaseCode.java
  src/main/java/neordinary/dofarming/common/code/BaseErrorCode.java
  src/main/java/neordinary/dofarming/common/code/ErrorReasonDTO.java
  src/main/java/neordinary/dofarming/common/code/ReasonDTO.java
  src/main/java/neordinary/dofarming/common/code/status/ErrorStatus.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
  src/main/java/neordinary/dofarming/common/config/AppConfig.java
  src/main/java/neordinary/dofarming/common/config/RedisConfig.java
  src/main/java/neordinary/dofarming/common/config/SecurityConfig.java
  src/main/java/neordinary/dofarming/common/config/SwaggerConfig.java
  src/main/java/neordinary/dofarming/common/exceptions/BaseException.java
  src/main/java/neordinary/dofarming/common/exceptions/ExceptionAdvice.java
  src/main/java/neordinary/dofarming/common/exceptions/handler/CustomAccessDeniedHandler.java
  src/main/java/neordinary/dofarming/common/exceptions/handler/CustomAuthenticationEntryPoint.java
  src/main/java/neordinary/dofarming/common/exceptions/handler/ExceptionHandler.java
  src/main/java/neordinary/dofarming/domain/user/User.java
  src/main/java/neordinary/dofarming/domain/user/enums/Permission.java
  src/main/java/neordinary/dofarming/domain/user/enums/Role.java
  src/main/java/neordinary/dofarming/domain/user/enums/SocialType.java
  src/main/java/neordinary/dofarming/domain/user/repository/UserJpaRepository.java
  src/main/java/neordinary/dofarming/utils/ApplicationAuditAware.java
  src/main/java/neordinary/dofarming/utils/RedisProvider.java
  src/main/java/neordinary/dofarming/utils/jwt/JwtAuthenticationFilter.java
  src/main/java/neordinary/dofarming/utils/jwt/JwtProvider.java
  src/main/java/neordinary/dofarming/utils/jwt/LogoutService.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :books: ADD

#4 [ci/#3] ci/cd 구축
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/develop_dev.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/resources/application-dev.yml
Labels: :sparkles: feature, :construction_worker: ci

#5 [ci/#3] ci/cd 구축
  src/main/resources/application-dev.yml
Labels: :sparkles: feature, :construction_worker: ci

#6 [ci/#3] https 설정 추가
  src/main/resources/application-dev.yml
Labels: :recycle: refactor, :construction_worker: ci

#8 [setting/#7] entity 설계
  src/main/java/neordinary/dofarming/api/controller/category/CategoryController.java
  src/main/java/neordinary/dofarming/api/controller/mission/MissionController.java
  src/main/java/neordinary/dofarming/api/controller/question/QuestionController.java
  src/main/java/neordinary/dofarming/api/controller/user/UserController.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryService.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/mission/MissionService.java
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionService.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/user/UserService.java
  src/main/java/neordinary/dofarming/api/service/user/UserServiceImpl.java
  src/main/java/neordinary/dofarming/domain/category/Category.java
  src/main/java/neordinary/dofarming/domain/category/repository/CategoryJpaRepository.java
  src/main/java/neordinary/dofarming/domain/mapping/user_category/UserCategory.java
  src/main/java/neordinary/dofarming/domain/mapping/user_category/UserCategoryId.java
  src/main/java/neordinary/dofarming/domain/mapping/user_category/repository/UserCategoryJpaRepository.java
  src/main/java/neordinary/dofarming/domain/mapping/user_mission/UserMission.java
  src/main/java/neordinary/dofarming/domain/mapping/user_mission/UserMissionJpaRepository.java
  src/main/java/neordinary/dofarming/domain/mission/Mission.java
  src/main/java/neordinary/dofarming/domain/mission/repository/MissionJpaRepository.java
  src/main/java/neordinary/dofarming/domain/question/Question.java
  src/main/java/neordinary/dofarming/domain/question/repository/QuestionJpaRepository.java
  src/main/java/neordinary/dofarming/domain/user/User.java
  src/main/java/neordinary/dofarming/domain/user/repository/UserJpaRepository.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature

#9 [setting/#7] entity 설계
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#13 [feat/#10] S3 기능 추가
  build.gradle
  src/main/java/neordinary/dofarming/api/controller/user/UserController.java
  src/main/java/neordinary/dofarming/api/controller/user/dto/response/PatchUserRes.java
  src/main/java/neordinary/dofarming/api/service/user/UserService.java
  src/main/java/neordinary/dofarming/api/service/user/UserServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/ErrorStatus.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
  src/main/java/neordinary/dofarming/common/config/S3Config.java
  src/main/java/neordinary/dofarming/domain/user/User.java
  src/main/java/neordinary/dofarming/utils/s3/S3Provider.java
  src/main/java/neordinary/dofarming/utils/s3/dto/S3UploadRequest.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: :sparkles: feature

#18 [feat/#13] 마이페이지 조회 추가
  src/main/java/neordinary/dofarming/api/controller/user/UserController.java
  src/main/java/neordinary/dofarming/api/controller/user/dto/response/GetUserRes.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/user/UserService.java
  src/main/java/neordinary/dofarming/api/service/user/UserServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
Labels: :sparkles: feature

#19 [refactor/#17] category, user_category 테이블 수정
  src/main/java/neordinary/dofarming/api/controller/category/CategoryController.java
  src/main/java/neordinary/dofarming/api/controller/category/dto/response/CategoryResponseDto.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryService.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryServiceImpl.java
  src/main/java/neordinary/dofarming/domain/category/Category.java
  src/main/java/neordinary/dofarming/domain/mapping/user_category/UserCategory.java
  src/main/java/neordinary/dofarming/domain/mapping/user_category/repository/UserCategoryJpaRepository.java
Labels: :recycle: refactor

#20 [feat/#16] 개선하고 싶은 카테고리 조회
  src/main/java/neordinary/dofarming/api/controller/category/CategoryController.java
  src/main/java/neordinary/dofarming/api/controller/category/dto/response/CategoriesResponseDto.java
  src/main/java/neordinary/dofarming/api/controller/category/dto/response/CategoryDto.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryService.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryServiceImpl.java
Labels: :sparkles: feature

#26 [refactor/#24] 미션 추천 API 수정
  src/main/java/neordinary/dofarming/api/controller/mission/MissionController.java
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/ErrorStatus.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
Labels: :recycle: refactor

#29 [feat/#27] 질문 응답 저장하기
  src/main/java/neordinary/dofarming/api/controller/question/QuestionController.java
  src/main/java/neordinary/dofarming/api/controller/question/dto/request/QuestionRequestDto.java
  src/main/java/neordinary/dofarming/api/controller/question/dto/response/QuestionResponseDto.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionService.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/ErrorStatus.java
  src/main/java/neordinary/dofarming/common/exceptions/handler/QuestionHandler.java
  src/main/java/neordinary/dofarming/domain/question/Question.java
Labels: :sparkles: feature

#33 [refactor/#31] 응답 통일 & 스웨거 설명
  src/main/java/neordinary/dofarming/api/controller/category/CategoryController.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
Labels: :recycle: refactor

#41 [feat/#34] 카테고리 별 점수 비율 조회
  src/main/java/neordinary/dofarming/api/controller/question/QuestionController.java
  src/main/java/neordinary/dofarming/api/controller/question/dto/response/UserCategoryResponseDto.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionService.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
Labels: :sparkles: feature

#43 [feat/#39] 추가 정보 입력 기능 추가
  src/main/java/neordinary/dofarming/api/controller/auth/dto/response/PostSocialRes.java
  src/main/java/neordinary/dofarming/api/controller/user/UserController.java
  src/main/java/neordinary/dofarming/api/controller/user/dto/response/PatchUserRes.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthConverter.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/user/UserService.java
  src/main/java/neordinary/dofarming/api/service/user/UserServiceImpl.java
  src/main/java/neordinary/dofarming/common/code/status/SuccessStatus.java
  src/main/java/neordinary/dofarming/domain/user/User.java
Labels: :sparkles: feature

#45 [refactor/#42] 개선하고 싶은 카테고리 조회 시 카테고리 별 점수 비율 같이 조회
  src/main/java/neordinary/dofarming/api/controller/category/CategoryController.java
  src/main/java/neordinary/dofarming/api/controller/category/dto/response/CategoryDto.java
  src/main/java/neordinary/dofarming/api/controller/question/dto/response/UserCategoryResponseDto.java
  src/main/java/neordinary/dofarming/api/service/category/CategoryServiceImpl.java
  src/main/java/neordinary/dofarming/api/service/question/QuestionServiceImpl.java
  src/main/java/neordinary/dofarming/domain/category/repository/CategoryJpaRepository.java
Labels: :recycle: refactor

#46 [refactor/#44] 마이페이지 조회 시 이번 주 지난 주 성공률 정보 추가
  src/main/java/neordinary/dofarming/api/controller/user/dto/response/GetPointRes.java
  src/main/java/neordinary/dofarming/api/controller/user/dto/response/GetUserRes.java
  src/main/java/neordinary/dofarming/api/service/auth/AuthConverter.java
  src/main/java/neordinary/dofarming/api/service/user/UserServiceImpl.java
  src/main/java/neordinary/dofarming/domain/mapping/user_mission/UserMissionJpaRepository.java
Labels: :recycle: refactor

#51 [refactor/#50] MissionController 트랜잭셔널 설정 변경
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
Labels: :recycle: refactor

#54 [refactor/#50] UserController 수정
  src/main/java/neordinary/dofarming/api/controller/user/UserController.java
Labels: :recycle: refactor

#59 [feat/#58] 날짜별 미션 조회 수정
  src/main/java/neordinary/dofarming/api/controller/mission/MissionController.java
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#61 [refactor/#60] 날짜별 미션 조회 수정
  src/main/java/neordinary/dofarming/api/service/mission/MissionServiceImpl.java
Labels: :recycle: refactor
